apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: bankapp
spec:
  selector:
    app.kubernetes.io/name: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306